executable = ./scripts/ground_sam.sh
arguments = examples/$(dir)
error = ./logs/$(subject)/ground_sam.err
output = ./logs/$(subject)/ground_sam.out
log = ./logs/$(subject)/ground_sam.log

request_memory = 20000
request_disk = 10G
request_cpus = 8
request_gpus = 1
requirements = (TARGET.CUDACapability > 7.5 && UtsnameNodename =!= "g095" && UtsnameNodename =!= "g093" && TARGET.CUDAGlobalMemoryMb > 60000 && CUDADeviceName == "NVIDIA A100-SXM4-80GB")

queue dir,subject from ./clusters/subjects.txt