executable = ./scripts/test_multi_concepts.sh
arguments = $(dir)

error = ./logs/$(subject)/test_multi_concepts.err
output = ./logs/$(subject)/test_multi_concepts.out
log = ./logs/$(subject)/test_multi_concepts.log

request_memory = 20000
request_disk = 10G
request_cpus = 8
request_gpus = 1
requirements = (TARGET.CUDACapability > 7.5 && UtsnameNodename =!= "g095" && UtsnameNodename =!= "g093" && TARGET.CUDAGlobalMemoryMb > 30000 && CUDADeviceName != "NVIDIA H100 80GB HBM3" && CUDADeviceName != "NVIDIA H100")

queue dir,subject from ./clusters/subjects.txt